apiVersion: apps/v1
kind: Deployment
metadata:
    name: t-cart-shop-app
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template: # template for the pods
      metadata:
        labels:
          app: web
      spec:
        containers:
          - name: t-cart-shop-cont
            image: ${REPOSITORY_TAG}
            resources:
              requests:
                memory: 512Mi
                cpu: 0.5
---                       
apiVersion: v1
kind: Service
metadata:
  name: t-cart-svc
spec:
   selector:
      app: web
   ports:
        - name: http
          port: 80
     
   type: ClusterIP
